jobs:
  - name: transfers
    query_id: 5876393
    outfile: transfers.parquet
  - name: transfers_cex_flags
    query_id: 5884144
    outfile: transfers_cex_flags.parquet
  - name: uniswap_swaps
    query_id: 5876396
    outfile: uniswap_swaps.parquet
  - name: eth_blocks
    query_id: 5876400
    outfile: eth_blocks.parquet
  - name: address_first
    query_id: 5876406
    outfile: address_first.parquet
